project_root:

output_dir: ${project_root}/outputs
model_weights_dir: ${project_root}/model_weights

dataset:
  # - name: "xjtu_1"
  #   path: "/workspaces/CaiZi/dataset/xjtu_1.txt"

  # - name: "qi_wang"
  #   path: "/workspaces/CaiZi/dataset/qi_wang.txt"

  # - name: "shu_wang"
  #   path: "/workspaces/CaiZi/dataset/shu_wang.txt"

  # - name: "hai_zi_wang"
  #   path: "/workspaces/CaiZi/dataset/hai_zi_wang.txt"

  #- name: "the_verdict"
  #  path: "/workspaces/CaiZi/dataset/the_verdict.txt"

  - name: "tiny_shakespeare"
    path: "/workspaces/CaiZi/dataset/tiny_shakespeare.txt"

train_ratio: 0.9

124M:
  vocab_size: 50304 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
  block_size: 1024 # maximum length of the text to be generated
  stride: 1024 #  window stride for the dataset. 
  dimension_embedding: 768 # embedding dimension
  num_layers: 12 # number of layers
  num_headers: 12 # number of heads
  drop_rate: 0.0 # dropout rate
  bias: False # whether to use bias in attention layer

  openai_gpt_dir: ${model_weights_dir}/openai


ray_train:
  num_workers:  1
  use_gpu: True
  num_gpus_per_worker: 1
  num_cpus_per_worker: 1

  check_frequency: 1
  total_tokens_per_logical_batch_per_worker: 524288   # 2^19,~0.5M, in number of tokens
  physical_training_batch_size_per_worker: 16
  num_epoch_per_worker: 80

  physical_validate_batch_size_per_worker: 1

  storage_path: ${output_dir}/gpt2
  name: "124M"

  start_context: "To be, or not to be: that is the question."
  
  resume_training: False
  best_checkpoint_dir: ${model_weights_dir}/best_checkpoint
  
  weight_decay: 0.1
  warmup_steps: 2e3
  max_steps: 6e5
  max_lr: 6e-4
  min_lr: 6e-5

  data_type: "bfloat16"




 
  

  
  
  
  

