project_root:

output_dir: ${project_root}/outputs

dataset:
  # - name: "xjtu_1"
  #   path: "/workspaces/CaiZi/dataset/xjtu_1.txt"

  # - name: "qi_wang"
  #   path: "/workspaces/CaiZi/dataset/qi_wang.txt"

  # - name: "shu_wang"
  #   path: "/workspaces/CaiZi/dataset/shu_wang.txt"

  # - name: "hai_zi_wang"
  #   path: "/workspaces/CaiZi/dataset/hai_zi_wang.txt"

  - name: "the_verdict"
    path: "/workspaces/CaiZi/dataset/the_verdict.txt"

train_ratio: 0.9

124M:
  vocab_size: 50257 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
  block_size: 256 # maximum length of the text to be generated
  stride: 256 #  window stride for the dataset. The default value is 1, which means that the dataset is a contiguous block of text.
  dimension_embedding: 768 # embedding dimension
  num_layers: 12 # number of layers
  num_headers: 12 # number of heads
  drop_rate: 0.1 # dropout rate
  qkv_bias: False # whether to use bias in attention layer
  

ray_train:
  num_workers: 1
  use_gpu: True
  num_gpus_per_worker: 1
  num_cpus_per_worker: 1

  check_frequency: 5
  batch_size_per_worker: 4
  num_epoch_per_worker: 15

  storage_path: ${output_dir}/gpt2
  name: "124M"

  resume_training: False



 
  

  
  
  
  

