project_root:

output_dir: ${project_root}/outputs
model_weights_dir: ${project_root}/model_weights

dataset:
  # - name: "xjtu_1"
  #   path: "/workspaces/CaiZi/dataset/xjtu_1.txt"

  # - name: "qi_wang"
  #   path: "/workspaces/CaiZi/dataset/qi_wang.txt"

  # - name: "shu_wang"
  #   path: "/workspaces/CaiZi/dataset/shu_wang.txt"

  # - name: "hai_zi_wang"
  #   path: "/workspaces/CaiZi/dataset/hai_zi_wang.txt"

  #- name: "the_verdict"
  #  path: "/workspaces/CaiZi/dataset/the_verdict.txt"

  - name: "tiny_shakespeare"
    path: "/workspaces/CaiZi/dataset/tiny_shakespeare.txt"

train_ratio: 0.9

124M:
  vocab_size: 65 # GPT-2 vocab_size of 50257, padded up to nearest multiple of 64 for efficiency
  block_size: 256 # maximum length of the text to be generated
  stride: 256 #  window stride for the dataset. 
  dimension_embedding: 384 # embedding dimension
  num_layers: 6 # number of layers
  num_headers: 6 # number of heads
  drop_rate: 0.2 # dropout rate
  bias: False # whether to use bias in attention layer

  openai_gpt_dir: ${model_weights_dir}/openai


ray_data:
  # Tokenizer
  tokenizer_class : CharTokenizer
  

ray_train:
  num_workers:  1
  use_gpu: True
  num_gpus_per_worker: 1
  num_cpus_per_worker: 1

  check_frequency: 1

  gradient_accumulation_steps: 1
  physical_training_batch_size_per_worker: 64
  physical_validate_batch_size_per_worker: 64
  num_epoch_per_worker: 80

  # Training output
  storage_path: ${output_dir}/gpt2
  name: "shakespeare"

  # checkpoint dir
  best_checkpoint_dir: ${model_weights_dir}/best_checkpoint

  start_context: "To be, or not to be: that is the question."
  
  resume_training: False
  
  # Optimizer
  weight_decay: 0.1

  # Scheduler
  warmup_steps: 100
  max_steps: 5000
  max_lr: 1e-3
  min_lr: 6e-5
  beta1: 0.9
  beta2: 0.99
  decay_lr: False

  # Floating point precision
  data_type: bfloat16



 
  

  
  
  
  

